tests/test_usuario_repo.py:35:49: error: Argument 1 to "obter_usuario_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_simple.py:24:56: error: Argument 1 to "obter_plano_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_inscricao.py:36:54: error: Argument 1 to "deletar_inscricao_plano" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_inscricao.py:44:18: error: Argument "id_plano" to "InscricaoPlano" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_dados_pagamento.py:33:15: error: Item "None" of "Plano | None" has no attribute "nome_plano"  [union-attr]
tests/test_servico_repo.py:26:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_servico_repo.py:39:21: error: Unexpected keyword argument "endereco" for "Prestador"  [call-arg]
tests/test_servico_repo.py:40:16: error: Argument "id" to "Prestador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:47:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_servico_repo.py:79:43: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:123:42: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:179:24: error: Argument "id_servico" to "Servico" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:190:43: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:191:16: error: Item "None" of "Servico | None" has no attribute "titulo"  [union-attr]
tests/test_servico_repo.py:192:16: error: Item "None" of "Servico | None" has no attribute "valor_base"  [union-attr]
tests/test_servico_repo.py:210:37: error: Argument 1 to "deletar_servico" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:213:40: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:132:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:196:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:279:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:304:42: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:360:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:371:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:381:42: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:382:16: error: Argument "id" to "Prestador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:103:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:194:43: error: Argument 1 to "obter_anuncio_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:336:31: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:468:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_produto_repo.py:58:9: error: Item "None" of "Produto | None" has no attribute "nome"  [union-attr]
tests/test_produto_repo.py:59:9: error: Item "None" of "Produto | None" has no attribute "preco"  [union-attr]
tests/test_produto_repo.py:60:9: error: Item "None" of "Produto | None" has no attribute "descricao"  [union-attr]
tests/test_produto_repo.py:61:9: error: Item "None" of "Produto | None" has no attribute "quantidade"  [union-attr]
tests/test_produto_repo.py:62:37: error: Argument 1 to "atualizar_produto" has incompatible type "Produto | None"; expected "Produto"  [arg-type]
tests/test_produto_repo.py:65:16: error: Item "None" of "Produto | None" has no attribute "nome"  [union-attr]
tests/test_produto_repo.py:66:16: error: Item "None" of "Produto | None" has no attribute "preco"  [union-attr]
tests/test_produto_repo.py:67:16: error: Item "None" of "Produto | None" has no attribute "descricao"  [union-attr]
tests/test_produto_repo.py:68:16: error: Item "None" of "Produto | None" has no attribute "quantidade"  [union-attr]
tests/test_orcamento_servico_repo.py:57:16: error: Argument "id" to "Cliente" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_servico_repo.py:203:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_servico_repo.py:214:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_servico_repo.py:273:9: error: Item "None" of "OrcamentoServico | None" has no attribute "status"  [union-attr]
tests/test_orcamento_servico_repo.py:274:49: error: Argument 1 to "atualizar_orcamento_servico" has incompatible type "OrcamentoServico | None"; expected "OrcamentoServico"  [arg-type]
tests/test_orcamento_repo.py:228:5: error: Unsupported class scoped import  [misc]
tests/test_notificacao_repo.py:59:51: error: Argument 1 to "obter_notificacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:89:51: error: Argument 1 to "obter_notificacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:139:59: error: Argument 1 to "obter_notificacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:140:9: error: Item "None" of "Notificacao | None" has no attribute "mensagem"  [union-attr]
tests/test_notificacao_repo.py:141:43: error: Argument 1 to "atualizar_notificacao" has incompatible type "Notificacao | None"; expected "Notificacao"  [arg-type]
tests/test_notificacao_repo.py:159:29: error: Argument 1 to "deletar" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_avaliacao_repo.py:56:16: error: Argument "id" to "Cliente" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_avaliacao_repo.py:147:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_avaliacao_repo.py:158:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_avaliacao_repo.py:181:47: error: Argument 1 to "obter_avaliacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_avaliacao_repo.py:310:9: error: Item "None" of "Avaliacao | None" has no attribute "descricao"  [union-attr]
tests/test_avaliacao_repo.py:311:41: error: Argument 1 to "atualizar_avaliacao" has incompatible type "Avaliacao | None"; expected "Avaliacao"  [arg-type]
tests/test_administrador_repo.py:128:18: error: Assignment to variable "e" outside except: block  [misc]
tests/test_administrador_repo.py:131:54: error: Trying to read deleted variable "e"  [misc]
tests/test_administrador_repo.py:138:23: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:141:31: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:145:65: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:154:86: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
utils/error_handlers.py:11:1: error: Cannot find implementation or library stub for module named "infrastructure.logging"  [import-not-found]
utils/error_handlers.py:11:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
routes/publico/publico_routes.py:533:9: error: Need type annotation for "campos_erro" (hint: "campos_erro: dict[<type>, <type>] = ...")  [var-annotated]
routes/publico/publico_routes.py:538:21: error: Value of type "tuple[int | str, ...] | None" is not indexable  [index]
routes/publico/publico_routes.py:540:24: error: Item "int" of "int | str | Any" has no attribute "capitalize"  [union-attr]
routes/publico/publico_routes.py:584:30: error: Incompatible types in assignment (expression has type "str", target has type "Request")  [assignment]
routes/publico/publico_routes.py:638:29: error: Item "int" of "int | str" has no attribute "capitalize"  [union-attr]
routes/publico/publico_routes.py:697:15: error: Module has no attribute "obter_usuario_por_token"; maybe "obter_usuario_por_id", "obter_usuario_por_email", or "obter_usuarios_por_pagina"?  [attr-defined]
routes/publico/publico_routes.py:717:2: error: Name "exibir_perfil_publico" already defined on line 712  [no-redef]
routes/publico/publico_routes.py:722:2: error: Name "exibir_perfil_publico" already defined on line 712  [no-redef]
routes/publico/publico_routes.py:771:23: error: Missing positional argument "usuario_id" in call to "obter_mensagem"  [call-arg]
routes/prestador/prestador_servicos.py:25:9: error: "Servico" has no attribute "foto_principal"  [attr-defined]
routes/prestador/prestador_servicos.py:25:55: error: "Servico" has no attribute "id"  [attr-defined]
routes/prestador/prestador_servicos.py:51:15: error: Unexpected keyword argument "id" for "Servico"  [call-arg]
routes/prestador/prestador_servicos.py:51:15: error: Unexpected keyword argument "data_cadastro" for "Servico"  [call-arg]
routes/prestador/prestador_servicos.py:51:15: error: Unexpected keyword argument "foto" for "Servico"  [call-arg]
routes/prestador/prestador_perfil.py:72:2: error: Name "alterar_foto" already defined on line 66  [no-redef]
routes/prestador/prestador_pagamento.py:178:21: error: Unexpected keyword argument "id_prestador" for "add_card" of "PaymentService"  [call-arg]
routes/prestador/prestador_pagamento.py:208:22: error: "CartaoCredito" has no attribute "id_prestador"  [attr-defined]
routes/prestador/prestador_pagamento.py:261:22: error: "CartaoCredito" has no attribute "id_prestador"  [attr-defined]
routes/prestador/prestador_pagamento.py:300:51: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:29:22: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:30:22: error: Argument 1 to "float" has incompatible type "UploadFile | str | Buffer | SupportsFloat | SupportsIndex"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:53:22: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:54:22: error: Argument 1 to "float" has incompatible type "UploadFile | str | Buffer | SupportsFloat | SupportsIndex"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:96:22: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_planos.py:86:12: error: Unsupported operand types for > ("float" and "None")  [operator]
routes/fornecedor/fornecedor_planos.py:86:12: error: Unsupported operand types for < ("float" and "None")  [operator]
routes/fornecedor/fornecedor_planos.py:86:12: error: Unsupported left operand type for > ("None")  [operator]
routes/fornecedor/fornecedor_planos.py:86:12: note: Both left and right operands are unions
routes/fornecedor/fornecedor_planos.py:86:38: error: Item "None" of "Plano | None" has no attribute "valor_mensal"  [union-attr]
routes/fornecedor/fornecedor_planos.py:150:50: error: Argument 1 to "deletar_inscricao_plano" has incompatible type "int | None"; expected "int"  [arg-type]
routes/fornecedor/fornecedor_planos.py:232:17: error: Module has no attribute "obter_historico_planos_por_fornecedor"  [attr-defined]
routes/fornecedor/fornecedor_mensagens.py:15:46: error: Value of type "dict[Any, Any] | None" is not indexable  [index]
routes/fornecedor/fornecedor_mensagens.py:25:17: error: Module has no attribute "obter_mensagens_enviadas"  [attr-defined]
routes/fornecedor/fornecedor_mensagens.py:25:56: error: Item "dict[Any, Any]" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:25:56: error: Item "None" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:36:52: error: Item "dict[Any, Any]" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:36:52: error: Item "None" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:47:5: error: Module has no attribute "enviar_mensagem"; maybe "deletar_mensagem", "inserir_mensagem", or "obter_mensagem"?  [attr-defined]
routes/fornecedor/fornecedor_mensagens.py:47:35: error: Item "dict[Any, Any]" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:47:35: error: Item "None" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
tests/test_publico_routes.py:85:9: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_publico_routes.py:86:9: error: Dict entry 1 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_fornecedor_produtos.py:32:65: error: Argument "data" to "post" of "TestClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | Iterable[str] | bytes] | None"  [arg-type]
tests/test_fornecedor_produtos.py:46:68: error: Argument "data" to "post" of "TestClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | Iterable[str] | bytes] | None"  [arg-type]
tests/test_fornecedor_planos.py:28:64: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_fornecedor_planos.py:50:64: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_fornecedor_planos.py:61:64: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
Found 109 errors in 24 files (checked 146 source files)
