dados_para_testes_rotas/teste_rotas_mensagens.py:6:1: error: Library stubs not installed for "requests"  [import-untyped]
dados_para_testes_rotas/teste_rotas_mensagens.py:6:1: note: Hint: "python3 -m pip install types-requests"
dados_para_testes_rotas/teste_rotas_mensagens.py:6:1: note: (or run "mypy --install-types" to install all missing stub packages)
dados_para_testes_rotas/teste_rotas_mensagens.py:6:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
tests/test_usuario_repo.py:23:43: error: Argument 1 to "obter_usuario_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_usuario_repo.py:34:49: error: Argument 1 to "obter_usuario_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_usuario_repo.py:41:43: error: Argument 1 to "obter_usuario_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_usuario_repo.py:42:16: error: Item "None" of "Usuario | None" has no attribute "nome"  [union-attr]
tests/test_usuario_repo.py:79:51: error: Argument 1 to "obter_usuario_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_simple.py:24:56: error: Argument 1 to "obter_plano_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_inscricao.py:36:54: error: Argument 1 to "deletar_inscricao_plano" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_inscricao.py:44:18: error: Argument "id_plano" to "InscricaoPlano" has incompatible type "int | None"; expected "int"  [arg-type]
dados_para_testes_rotas/test_dados_pagamento.py:33:15: error: Item "None" of "Plano | None" has no attribute "nome_plano"  [union-attr]
tests/test_servico_repo.py:26:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_servico_repo.py:39:21: error: Unexpected keyword argument "endereco" for "Prestador"  [call-arg]
tests/test_servico_repo.py:40:16: error: Argument "id" to "Prestador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:47:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_servico_repo.py:79:43: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:123:42: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:179:24: error: Argument "id_servico" to "Servico" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:190:43: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:191:16: error: Item "None" of "Servico | None" has no attribute "titulo"  [union-attr]
tests/test_servico_repo.py:192:16: error: Item "None" of "Servico | None" has no attribute "valor_base"  [union-attr]
tests/test_servico_repo.py:210:37: error: Argument 1 to "deletar_servico" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_servico_repo.py:213:40: error: Argument 1 to "obter_servico_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:53:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:69:26: error: Argument "valor_mensal" to "Plano" has incompatible type "str"; expected "float | None"  [arg-type]
tests/test_inscricao_plano.py:77:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:89:21: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:113:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:126:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:138:42: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:186:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:198:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:209:42: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:210:16: error: Argument "id" to "Prestador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:237:26: error: Argument "id_plano" to "InscricaoPlano" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:263:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:275:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:286:42: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:287:16: error: Argument "id" to "Prestador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:312:22: error: Argument "id_plano" to "InscricaoPlano" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:321:22: error: Argument "id_plano" to "InscricaoPlano" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:338:44: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_inscricao_plano.py:349:38: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_inscricao_plano.py:359:42: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Prestador"  [call-arg]
tests/test_inscricao_plano.py:360:16: error: Argument "id" to "Prestador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_inscricao_plano.py:384:22: error: Argument "id_plano" to "InscricaoPlano" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:21:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:33:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:48:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:70:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:82:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:98:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:122:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:134:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:150:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:175:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:177:22: error: Missing positional arguments "bairro", "cidade", "estado", "tipo_usuario" in call to "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:177:33: error: Argument 1 to "Fornecedor" has incompatible type "Callable[[object], int]"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:180:75: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:183:43: error: Argument 1 to "obter_anuncio_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:199:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:211:22: error: Unexpected keyword argument "endereco" for "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:212:16: error: Argument "id" to "Fornecedor" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:219:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_anuncio_repo.py:229:31: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:270:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:282:22: error: Unexpected keyword argument "endereco" for "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:283:16: error: Argument "id" to "Fornecedor" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:290:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_anuncio_repo.py:308:31: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:328:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:340:22: error: Unexpected keyword argument "endereco" for "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:341:16: error: Argument "id" to "Fornecedor" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:348:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_anuncio_repo.py:357:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:366:24: error: Argument "id_anuncio" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:368:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:378:43: error: Argument 1 to "obter_anuncio_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:392:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_anuncio_repo.py:404:22: error: Unexpected keyword argument "endereco" for "Fornecedor"  [call-arg]
tests/test_anuncio_repo.py:405:16: error: Argument "id" to "Fornecedor" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:412:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_anuncio_repo.py:421:27: error: Argument "id_fornecedor" to "Anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:429:35: error: Argument 1 to "deletar_anuncio" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_anuncio_repo.py:433:43: error: Argument 1 to "obter_anuncio_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_produto_repo.py:58:9: error: Item "None" of "Produto | None" has no attribute "nome"  [union-attr]
tests/test_produto_repo.py:59:9: error: Item "None" of "Produto | None" has no attribute "preco"  [union-attr]
tests/test_produto_repo.py:60:9: error: Item "None" of "Produto | None" has no attribute "descricao"  [union-attr]
tests/test_produto_repo.py:61:9: error: Item "None" of "Produto | None" has no attribute "quantidade"  [union-attr]
tests/test_produto_repo.py:62:37: error: Argument 1 to "atualizar_produto" has incompatible type "Produto | None"; expected "Produto"  [arg-type]
tests/test_produto_repo.py:65:16: error: Item "None" of "Produto | None" has no attribute "nome"  [union-attr]
tests/test_produto_repo.py:66:16: error: Item "None" of "Produto | None" has no attribute "preco"  [union-attr]
tests/test_produto_repo.py:67:16: error: Item "None" of "Produto | None" has no attribute "descricao"  [union-attr]
tests/test_produto_repo.py:68:16: error: Item "None" of "Produto | None" has no attribute "quantidade"  [union-attr]
tests/test_orcamento_servico_repo.py:57:16: error: Argument "id" to "Cliente" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_servico_repo.py:203:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_servico_repo.py:214:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_servico_repo.py:273:9: error: Item "None" of "OrcamentoServico | None" has no attribute "status"  [union-attr]
tests/test_orcamento_servico_repo.py:274:49: error: Argument 1 to "atualizar_orcamento_servico" has incompatible type "OrcamentoServico | None"; expected "OrcamentoServico"  [arg-type]
tests/test_orcamento_repo.py:33:30: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_repo.py:40:27: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:46:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_orcamento_repo.py:53:27: error: Argument "data_cadastro" to "Fornecedor" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:60:27: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_repo.py:67:27: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:73:19: error: Unexpected keyword argument "endereco" for "Cliente"  [call-arg]
tests/test_orcamento_repo.py:81:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_orcamento_repo.py:139:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_repo.py:141:27: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:145:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_orcamento_repo.py:147:27: error: Argument "data_cadastro" to "Fornecedor" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:151:21: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_repo.py:153:27: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:157:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Cliente"  [call-arg]
tests/test_orcamento_repo.py:158:16: error: Argument "id" to "Cliente" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:164:27: error: Argument "data_cadastro" to "Cliente" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:173:27: error: Argument "id_fornecedor" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:174:24: error: Argument "id_cliente" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:183:41: error: Argument 1 to "obter_orcamento_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:190:5: error: Unsupported class scoped import  [misc]
tests/test_orcamento_repo.py:231:21: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_repo.py:233:27: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:236:22: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Fornecedor"  [call-arg]
tests/test_orcamento_repo.py:238:27: error: Argument "data_cadastro" to "Fornecedor" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:242:21: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_orcamento_repo.py:244:27: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_orcamento_repo.py:247:19: error: Unexpected keyword argument "endereco" for "Cliente"  [call-arg]
tests/test_orcamento_repo.py:248:16: error: Argument "id" to "Cliente" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:255:22: error: "Usuario" has no attribute "endereco"  [attr-defined]
tests/test_orcamento_repo.py:264:27: error: Argument "id_fornecedor" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:265:24: error: Argument "id_cliente" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:276:16: error: Argument "id" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:277:27: error: Argument "id_fornecedor" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:278:24: error: Argument "id_cliente" to "Orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:289:45: error: Argument 1 to "obter_orcamento_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:290:16: error: Item "None" of "Orcamento | None" has no attribute "valor_estimado"  [union-attr]
tests/test_orcamento_repo.py:291:16: error: Item "None" of "Orcamento | None" has no attribute "status"  [union-attr]
tests/test_orcamento_repo.py:292:32: error: Item "None" of "Orcamento | None" has no attribute "descricao"  [union-attr]
tests/test_orcamento_repo.py:309:37: error: Argument 1 to "deletar_orcamento" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_orcamento_repo.py:312:41: error: Argument 1 to "obter_orcamento_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:59:51: error: Argument 1 to "obter_notificacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:89:51: error: Argument 1 to "obter_notificacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:139:59: error: Argument 1 to "obter_notificacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_notificacao_repo.py:140:9: error: Item "None" of "Notificacao | None" has no attribute "mensagem"  [union-attr]
tests/test_notificacao_repo.py:141:43: error: Argument 1 to "atualizar_notificacao" has incompatible type "Notificacao | None"; expected "Notificacao"  [arg-type]
tests/test_notificacao_repo.py:159:29: error: Argument 1 to "deletar" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_avaliacao_repo.py:56:16: error: Argument "id" to "Cliente" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_avaliacao_repo.py:147:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_avaliacao_repo.py:158:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_avaliacao_repo.py:181:47: error: Argument 1 to "obter_avaliacao_por_id" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_avaliacao_repo.py:310:9: error: Item "None" of "Avaliacao | None" has no attribute "descricao"  [union-attr]
tests/test_avaliacao_repo.py:311:41: error: Argument 1 to "atualizar_avaliacao" has incompatible type "Avaliacao | None"; expected "Avaliacao"  [arg-type]
tests/test_administrador_repo.py:26:28: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:33:31: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:53:24: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:53:140: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:54:24: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:54:144: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:55:24: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:55:144: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:61:66: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:62:66: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:77:28: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:79:63: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:82:77: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:98:19: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:98:127: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:99:20: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:99:130: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:103:61: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:107:103: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:112:70: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:115:18: error: Assignment to variable "e" outside except: block  [misc]
tests/test_administrador_repo.py:116:70: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:118:54: error: Trying to read deleted variable "e"  [misc]
tests/test_administrador_repo.py:125:23: error: Missing positional arguments "cep", "rua", "numero", "complemento", "bairro", "cidade", "estado" in call to "Usuario"  [call-arg]
tests/test_administrador_repo.py:128:31: error: Argument "data_cadastro" to "Usuario" has incompatible type "datetime"; expected "str | None"  [arg-type]
tests/test_administrador_repo.py:132:65: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
tests/test_administrador_repo.py:141:86: error: Argument "id_usuario" to "Administrador" has incompatible type "int | None"; expected "int"  [arg-type]
utils/error_handlers.py:11:1: error: Cannot find implementation or library stub for module named "infrastructure.logging"  [import-not-found]
routes/publico/publico_routes.py:533:9: error: Need type annotation for "campos_erro" (hint: "campos_erro: dict[<type>, <type>] = ...")  [var-annotated]
routes/publico/publico_routes.py:538:21: error: Value of type "tuple[int | str, ...] | None" is not indexable  [index]
routes/publico/publico_routes.py:540:24: error: Item "int" of "int | str | Any" has no attribute "capitalize"  [union-attr]
routes/publico/publico_routes.py:584:30: error: Incompatible types in assignment (expression has type "str", target has type "Request")  [assignment]
routes/publico/publico_routes.py:638:29: error: Item "int" of "int | str" has no attribute "capitalize"  [union-attr]
routes/publico/publico_routes.py:697:15: error: Module has no attribute "obter_usuario_por_token"; maybe "obter_usuario_por_id", "obter_usuario_por_email", or "obter_usuarios_por_pagina"?  [attr-defined]
routes/publico/publico_routes.py:717:2: error: Name "exibir_perfil_publico" already defined on line 712  [no-redef]
routes/publico/publico_routes.py:722:2: error: Name "exibir_perfil_publico" already defined on line 712  [no-redef]
routes/publico/publico_routes.py:771:23: error: Missing positional argument "usuario_id" in call to "obter_mensagem"  [call-arg]
routes/prestador/prestador_servicos.py:25:9: error: "Servico" has no attribute "foto_principal"  [attr-defined]
routes/prestador/prestador_servicos.py:25:55: error: "Servico" has no attribute "id"  [attr-defined]
routes/prestador/prestador_servicos.py:51:15: error: Unexpected keyword argument "id" for "Servico"  [call-arg]
routes/prestador/prestador_servicos.py:51:15: error: Unexpected keyword argument "data_cadastro" for "Servico"  [call-arg]
routes/prestador/prestador_servicos.py:51:15: error: Unexpected keyword argument "foto" for "Servico"  [call-arg]
routes/prestador/prestador_perfil.py:72:2: error: Name "alterar_foto" already defined on line 66  [no-redef]
routes/prestador/prestador_pagamento.py:178:21: error: Unexpected keyword argument "id_prestador" for "add_card" of "PaymentService"  [call-arg]
routes/prestador/prestador_pagamento.py:208:22: error: "CartaoCredito" has no attribute "id_prestador"  [attr-defined]
routes/prestador/prestador_pagamento.py:261:22: error: "CartaoCredito" has no attribute "id_prestador"  [attr-defined]
routes/prestador/prestador_pagamento.py:300:51: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:29:22: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:30:22: error: Argument 1 to "float" has incompatible type "UploadFile | str | Buffer | SupportsFloat | SupportsIndex"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:53:22: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:54:22: error: Argument 1 to "float" has incompatible type "UploadFile | str | Buffer | SupportsFloat | SupportsIndex"; expected "str | Buffer | SupportsFloat | SupportsIndex"  [arg-type]
routes/fornecedor/fornecedor_promocoes.py:96:22: error: Argument 1 to "int" has incompatible type "UploadFile | str | None"; expected "str | Buffer | SupportsInt | SupportsIndex | SupportsTrunc"  [arg-type]
routes/fornecedor/fornecedor_planos.py:86:12: error: Unsupported operand types for > ("float" and "None")  [operator]
routes/fornecedor/fornecedor_planos.py:86:12: error: Unsupported operand types for < ("float" and "None")  [operator]
routes/fornecedor/fornecedor_planos.py:86:12: error: Unsupported left operand type for > ("None")  [operator]
routes/fornecedor/fornecedor_planos.py:86:12: note: Both left and right operands are unions
routes/fornecedor/fornecedor_planos.py:86:38: error: Item "None" of "Plano | None" has no attribute "valor_mensal"  [union-attr]
routes/fornecedor/fornecedor_planos.py:150:50: error: Argument 1 to "deletar_inscricao_plano" has incompatible type "int | None"; expected "int"  [arg-type]
routes/fornecedor/fornecedor_planos.py:232:17: error: Module has no attribute "obter_historico_planos_por_fornecedor"  [attr-defined]
routes/fornecedor/fornecedor_mensagens.py:15:46: error: Value of type "dict[Any, Any] | None" is not indexable  [index]
routes/fornecedor/fornecedor_mensagens.py:25:17: error: Module has no attribute "obter_mensagens_enviadas"  [attr-defined]
routes/fornecedor/fornecedor_mensagens.py:25:56: error: Item "dict[Any, Any]" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:25:56: error: Item "None" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:36:52: error: Item "dict[Any, Any]" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:36:52: error: Item "None" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:47:5: error: Module has no attribute "enviar_mensagem"; maybe "deletar_mensagem", "inserir_mensagem", or "obter_mensagem"?  [attr-defined]
routes/fornecedor/fornecedor_mensagens.py:47:35: error: Item "dict[Any, Any]" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
routes/fornecedor/fornecedor_mensagens.py:47:35: error: Item "None" of "dict[Any, Any] | None" has no attribute "id"  [union-attr]
tests/test_publico_routes.py:85:9: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_publico_routes.py:86:9: error: Dict entry 1 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_fornecedor_produtos.py:32:65: error: Argument "data" to "post" of "TestClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | Iterable[str] | bytes] | None"  [arg-type]
tests/test_fornecedor_produtos.py:46:68: error: Argument "data" to "post" of "TestClient" has incompatible type "dict[str, object]"; expected "Mapping[str, str | Iterable[str] | bytes] | None"  [arg-type]
tests/test_fornecedor_planos.py:28:64: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_fornecedor_planos.py:50:64: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
tests/test_fornecedor_planos.py:61:64: error: Dict entry 0 has incompatible type "str": "int"; expected "str": "Iterable[str] | bytes"  [dict-item]
Found 225 errors in 25 files (checked 146 source files)
